[package]
name = "etcd-json"
version = "0.1.0"
authors = ["Aurojit Panda <apanda@cs.berkeley.edu>"]

[dependencies]
serde_json=">=1.0.2"
serde=">=1.0.9"
serde_derive=">=1.0.9"
base64="*"
hyper=">=0.11.1"
tokio-core=">=0.1.8"
futures=">=0.1.14"
